# Generated by Django 2.2.9 on 2022-05-05 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendimento',
            name='Card',
        ),
        migrations.AddField(
            model_name='atendimento',
            name='card',
            field=models.ManyToManyField(to='api.Card'),
        ),
        migrations.AlterField(
            model_name='elementocomunicativo',
            name='preceptor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elemento_preceptor', to=settings.AUTH_USER_MODEL),
        ),
    ]
